#!/usr/bin/env bash
while read line
do
    [[ "$line" = "\#*" ]] && continue
	echo "===================================="
	[[ "$line" = "\#*" ]] & echo "Running: " $line
	echo $line | python h5ql.py| tr ">" "\n"
done < $1
echo "===================================="
echo "H5QL Scripting Interface"
cat info.h5ql|python h5ql.py| sed -e 's/>//'
echo "===================================="
exit
